# Form implementation generated from reading ui file 'ui/start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 590)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabs.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabs.setStyleSheet("\n"
"QTabBar::tab {\n"
"        border: 1px solid black;\n"
"        padding: 10px;\n"
"        background-color: white;\n"
"        border-radius: 5px;\n"
"        font-family: Arial;\n"
"        font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        background: orange;\n"
"        font-weight: bold;\n"
"        color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background:  rgb(242, 75, 24);\n"
"        cursor: pointer;\n"
"}")
        self.tabs.setObjectName("tabs")
        self.crearordenTab = QtWidgets.QWidget()
        self.crearordenTab.setObjectName("crearordenTab")
        self.createorder = QtWidgets.QPushButton(parent=self.crearordenTab)
        self.createorder.setGeometry(QtCore.QRect(420, 320, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.createorder.setFont(font)
        self.createorder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.createorder.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.createorder.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.createorder.setAutoRepeatDelay(300)
        self.createorder.setObjectName("createorder")
        self.totalprice = QtWidgets.QLabel(parent=self.crearordenTab)
        self.totalprice.setGeometry(QtCore.QRect(570, 390, 211, 81))
        self.totalprice.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.totalprice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalprice.setObjectName("totalprice")
        self.searchbar = QtWidgets.QTextEdit(parent=self.crearordenTab)
        self.searchbar.setGeometry(QtCore.QRect(0, 0, 401, 41))
        self.searchbar.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"}")
        self.searchbar.setObjectName("searchbar")
        self.itemimg = QtWidgets.QLabel(parent=self.crearordenTab)
        self.itemimg.setGeometry(QtCore.QRect(20, 390, 131, 81))
        self.itemimg.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.itemimg.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.itemimg.setScaledContents(False)
        self.itemimg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.itemimg.setObjectName("itemimg")
        self.product_label = QtWidgets.QLabel(parent=self.crearordenTab)
        self.product_label.setGeometry(QtCore.QRect(430, 40, 91, 21))
        self.product_label.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.product_label.setObjectName("product_label")
        self.quantity_label = QtWidgets.QLabel(parent=self.crearordenTab)
        self.quantity_label.setGeometry(QtCore.QRect(570, 40, 91, 21))
        self.quantity_label.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.quantity_label.setObjectName("quantity_label")
        self.total_label = QtWidgets.QLabel(parent=self.crearordenTab)
        self.total_label.setGeometry(QtCore.QRect(700, 40, 81, 21))
        self.total_label.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.total_label.setObjectName("total_label")
        self.characteristics = QtWidgets.QLabel(parent=self.crearordenTab)
        self.characteristics.setGeometry(QtCore.QRect(160, 390, 391, 81))
        self.characteristics.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.characteristics.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.characteristics.setObjectName("characteristics")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.crearordenTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 60, 401, 311))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.items = QtWidgets.QListWidget(parent=self.horizontalLayoutWidget_3)
        self.items.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}")
        self.items.setObjectName("items")
        self.horizontalLayout_3.addWidget(self.items)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.crearordenTab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(420, 70, 371, 241))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.selecteditems = QtWidgets.QListWidget(parent=self.horizontalLayoutWidget_4)
        self.selecteditems.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}")
        self.selecteditems.setObjectName("selecteditems")
        self.horizontalLayout_5.addWidget(self.selecteditems)
        self.tabs.addTab(self.crearordenTab, "")
        self.ordenesTab = QtWidgets.QWidget()
        self.ordenesTab.setObjectName("ordenesTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.ordenesTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 401, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.verticalLayoutWidget)
        self.treeView.setStyleSheet("QTreeView{\n"
"    background-color: white;\n"
"}\n"
"\n"
"")
        self.treeView.setObjectName("treeView")
        self.treeView.header().setMinimumSectionSize(39)
        self.verticalLayout.addWidget(self.treeView)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 410, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(430, 50, 91, 21))
        self.label.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(570, 50, 91, 21))
        self.label_2.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(730, 50, 51, 21))
        self.label_3.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(310, 410, 211, 61))
        self.label_7.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(540, 340, 241, 51))
        self.label_8.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(430, 340, 101, 51))
        self.label_9.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 401, 41))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.listView = QtWidgets.QListView(parent=self.widget)
        self.listView.setGeometry(QtCore.QRect(430, 80, 351, 241))
        self.listView.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}")
        self.listView.setObjectName("listView")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 410, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_6.setAutoRepeatDelay(300)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.widget)
        self.tabs.addTab(self.ordenesTab, "")
        self.inventarioTab = QtWidgets.QWidget()
        self.inventarioTab.setObjectName("inventarioTab")
        self.treeView_2 = QtWidgets.QTreeView(parent=self.inventarioTab)
        self.treeView_2.setGeometry(QtCore.QRect(10, 60, 399, 401))
        self.treeView_2.setStyleSheet("QTreeView{\n"
"    background-color: white;\n"
"}\n"
"\n"
"")
        self.treeView_2.setObjectName("treeView_2")
        self.treeView_2.header().setMinimumSectionSize(39)
        self.label_4 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.label_4.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_10.setGeometry(QtCore.QRect(440, 50, 331, 51))
        self.label_10.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.guardarcambios = QtWidgets.QPushButton(parent=self.inventarioTab)
        self.guardarcambios.setGeometry(QtCore.QRect(430, 400, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.guardarcambios.setFont(font)
        self.guardarcambios.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.guardarcambios.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.guardarcambios.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.guardarcambios.setAutoRepeatDelay(300)
        self.guardarcambios.setObjectName("guardarcambios")
        self.listView_2 = QtWidgets.QListView(parent=self.inventarioTab)
        self.listView_2.setGeometry(QtCore.QRect(440, 120, 331, 261))
        self.listView_2.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"    \n"
"}")
        self.listView_2.setObjectName("listView_2")
        self.label_5 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_5.setGeometry(QtCore.QRect(460, 140, 111, 21))
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_6.setGeometry(QtCore.QRect(460, 180, 111, 21))
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_11.setGeometry(QtCore.QRect(460, 220, 111, 21))
        self.label_11.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_12.setGeometry(QtCore.QRect(460, 260, 111, 21))
        self.label_12.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.inventarioTab)
        self.lineEdit.setGeometry(QtCore.QRect(620, 140, 113, 22))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(parent=self.inventarioTab)
        self.spinBox.setGeometry(QtCore.QRect(620, 180, 42, 22))
        self.spinBox.setStyleSheet("QSpinBox{\n"
"    background-color: white;\n"
"}")
        self.spinBox.setObjectName("spinBox")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.inventarioTab)
        self.dateEdit.setGeometry(QtCore.QRect(620, 220, 110, 22))
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: white;\n"
"}")
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.inventarioTab)
        self.textEdit_2.setGeometry(QtCore.QRect(620, 300, 104, 71))
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_13 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_13.setGeometry(QtCore.QRect(460, 300, 111, 21))
        self.label_13.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.inventarioTab)
        self.doubleSpinBox.setGeometry(QtCore.QRect(620, 260, 62, 22))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    background-color: white;\n"
"}")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.tabs.addTab(self.inventarioTab, "")
        self.reportesTab = QtWidgets.QWidget()
        self.reportesTab.setObjectName("reportesTab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.reportesTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView_3 = QtWidgets.QListView(parent=self.gridLayoutWidget)
        self.listView_3.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}")
        self.listView_3.setObjectName("listView_3")
        self.gridLayout_2.addWidget(self.listView_3, 1, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.gridLayoutWidget)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
"                background-color: #333333;\n"
"                color: white;\n"
"                font-family: Arial;\n"
"                border-radius: 10px;\n"
"            }\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"                background-color: #444444;\n"
"                color: white;\n"
"                selection-background-color: orange;\n"
"                selection-color: white;\n"
"            }\n"
"            QCalendarWidget QAbstractItemView:disabled {\n"
"                color: #777777;\n"
"            }\n"
"            QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"                background-color: #555555;\n"
"            }\n"
"            QCalendarWidget QToolButton {\n"
"                color: white;\n"
"                background-color: #555555;\n"
"                border: none;\n"
"            }\n"
"\n"
" QCalendarWidget QToolButton::hover {\n"
"                background-color: orange;\n"
"                color: black;\n"
"            }\n"
"            QCalendarWidget QToolButton::pressed {\n"
"                background-color: #ff6600;\n"
"                color: white;\n"
"            }\n"
"            QCalendarWidget QToolButton::disabled {\n"
"                background-color: #555555;\n"
"                color: #777777;\n"
"            }")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_2.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.tabs.addTab(self.reportesTab, "")
        self.gridLayout.addWidget(self.tabs, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReportes = QtWidgets.QMenu(parent=self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuInventario = QtWidgets.QMenu(parent=self.menubar)
        self.menuInventario.setObjectName("menuInventario")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuInventario.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SellingSoftwareForMollysCookies"))
        self.createorder.setText(_translate("MainWindow", "Crear orden"))
        self.totalprice.setText(_translate("MainWindow", "Precio total"))
        self.itemimg.setText(_translate("MainWindow", "Imagen del producto"))
        self.product_label.setText(_translate("MainWindow", "Producto"))
        self.quantity_label.setText(_translate("MainWindow", "Cantidad"))
        self.total_label.setText(_translate("MainWindow", "Subtotal"))
        self.characteristics.setText(_translate("MainWindow", "Caracteristicas"))
        self.tabs.setTabText(self.tabs.indexOf(self.crearordenTab), _translate("MainWindow", "Crear"))
        self.pushButton_3.setText(_translate("MainWindow", "Eliminar orden"))
        self.label.setText(_translate("MainWindow", "Producto"))
        self.label_2.setText(_translate("MainWindow", "Cantidad"))
        self.label_3.setText(_translate("MainWindow", "Total"))
        self.label_7.setText(_translate("MainWindow", "Total a pagar"))
        self.label_8.setText(_translate("MainWindow", "Caracteristicas"))
        self.label_9.setText(_translate("MainWindow", "Imagen del producto"))
        self.pushButton_6.setText(_translate("MainWindow", "Eliminar item"))
        self.tabs.setTabText(self.tabs.indexOf(self.ordenesTab), _translate("MainWindow", "Ordenes"))
        self.label_4.setText(_translate("MainWindow", "Ingredientes"))
        self.label_10.setText(_translate("MainWindow", "Seleccionado"))
        self.guardarcambios.setText(_translate("MainWindow", "Guardar cambios"))
        self.label_5.setText(_translate("MainWindow", "Nombre"))
        self.label_6.setText(_translate("MainWindow", "Cantidad disponible"))
        self.label_11.setText(_translate("MainWindow", "Fecha de caducidad"))
        self.label_12.setText(_translate("MainWindow", "Precio unitario"))
        self.label_13.setText(_translate("MainWindow", "Descripción"))
        self.tabs.setTabText(self.tabs.indexOf(self.inventarioTab), _translate("MainWindow", "Inventario"))
        self.pushButton.setText(_translate("MainWindow", "Seleccionar"))
        self.tabs.setTabText(self.tabs.indexOf(self.reportesTab), _translate("MainWindow", "Reportes"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivos"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuInventario.setTitle(_translate("MainWindow", "Inventario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
