# Form implementation generated from reading ui file 'ui/start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabs.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabs.setStyleSheet("\n"
"QTabBar::tab {\n"
"        border: 1px solid black;\n"
"        padding: 10px;\n"
"        background-color: white;\n"
"        border-radius: 5px;\n"
"        font-family: Arial;\n"
"        font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        background: orange;\n"
"        font-weight: bold;\n"
"        color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background:  rgb(242, 75, 24);\n"
"        cursor: pointer;\n"
"}")
        self.tabs.setObjectName("tabs")
        self.ordenesTab = QtWidgets.QWidget()
        self.ordenesTab.setObjectName("ordenesTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.ordenesTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.verticalLayoutWidget)
        self.treeView.setStyleSheet("QTreeView{\n"
"    background-color: white;\n"
"\n"
"}")
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 330, 371, 54))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: white;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(430, 50, 91, 21))
        self.label.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(560, 50, 91, 21))
        self.label_2.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(690, 50, 91, 21))
        self.label_3.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(430, 100, 341, 41))
        self.label_4.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(430, 160, 341, 41))
        self.label_5.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(430, 220, 341, 41))
        self.label_6.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(420, 410, 371, 61))
        self.label_7.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(140, 410, 261, 61))
        self.label_8.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 410, 121, 61))
        self.label_9.setStyleSheet("QLabel{    \n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.widget)
        self.tabs.addTab(self.ordenesTab, "")
        self.inventarioTab = QtWidgets.QWidget()
        self.inventarioTab.setObjectName("inventarioTab")
        self.tabs.addTab(self.inventarioTab, "")
        self.reportesTab = QtWidgets.QWidget()
        self.reportesTab.setObjectName("reportesTab")
        self.tabs.addTab(self.reportesTab, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReportes = QtWidgets.QMenu(parent=self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuInventario = QtWidgets.QMenu(parent=self.menubar)
        self.menuInventario.setObjectName("menuInventario")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuInventario.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SellingSoftwareForMollysCookies"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Producto"))
        self.label_2.setText(_translate("MainWindow", "Cantidad"))
        self.label_3.setText(_translate("MainWindow", "Total"))
        self.label_4.setText(_translate("MainWindow", "Item1"))
        self.label_5.setText(_translate("MainWindow", "Item2"))
        self.label_6.setText(_translate("MainWindow", "Item3"))
        self.label_7.setText(_translate("MainWindow", "Cosas Generales"))
        self.label_8.setText(_translate("MainWindow", "Caracteristicas"))
        self.label_9.setText(_translate("MainWindow", "Imagen del producto"))
        self.tabs.setTabText(self.tabs.indexOf(self.ordenesTab), _translate("MainWindow", "Ordenes"))
        self.tabs.setTabText(self.tabs.indexOf(self.inventarioTab), _translate("MainWindow", "Inventario"))
        self.tabs.setTabText(self.tabs.indexOf(self.reportesTab), _translate("MainWindow", "Reportes"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivos"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuInventario.setTitle(_translate("MainWindow", "Inventario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
