# Form implementation generated from reading ui file 'ui/start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 589)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: #e8e8e8;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabs.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabs.setStyleSheet("\n"
"QTabBar::tab {\n"
"        border: 1px solid black;\n"
"        padding: 10px;\n"
"        background-color: white;\n"
"        border-radius: 5px;\n"
"        font-family: Arial;\n"
"        font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        background: orange;\n"
"        font-weight: bold;\n"
"        color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background:  rgb(242, 75, 24);\n"
"        cursor: pointer;\n"
"}")
        self.tabs.setObjectName("tabs")
        self.crearordenTab = QtWidgets.QWidget()
        self.crearordenTab.setObjectName("crearordenTab")
        self.crear_createorder_button = QtWidgets.QPushButton(parent=self.crearordenTab)
        self.crear_createorder_button.setGeometry(QtCore.QRect(420, 320, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.crear_createorder_button.setFont(font)
        self.crear_createorder_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.crear_createorder_button.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.crear_createorder_button.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: black;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    \n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.crear_createorder_button.setAutoRepeatDelay(300)
        self.crear_createorder_button.setObjectName("crear_createorder_button")
        self.crear_totalprice_button = QtWidgets.QLabel(parent=self.crearordenTab)
        self.crear_totalprice_button.setGeometry(QtCore.QRect(420, 390, 371, 81))
        self.crear_totalprice_button.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.crear_totalprice_button.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.crear_totalprice_button.setObjectName("crear_totalprice_button")
        self.searchbar = QtWidgets.QTextEdit(parent=self.crearordenTab)
        self.searchbar.setGeometry(QtCore.QRect(0, 10, 401, 41))
        self.searchbar.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"}")
        self.searchbar.setObjectName("searchbar")
        self.product_label = QtWidgets.QLabel(parent=self.crearordenTab)
        self.product_label.setGeometry(QtCore.QRect(430, 20, 81, 21))
        self.product_label.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.product_label.setObjectName("product_label")
        self.quantity_label = QtWidgets.QLabel(parent=self.crearordenTab)
        self.quantity_label.setGeometry(QtCore.QRect(560, 20, 81, 21))
        self.quantity_label.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.quantity_label.setObjectName("quantity_label")
        self.total_label = QtWidgets.QLabel(parent=self.crearordenTab)
        self.total_label.setGeometry(QtCore.QRect(700, 20, 71, 21))
        self.total_label.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.total_label.setObjectName("total_label")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.crearordenTab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 60, 401, 311))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.crear_items_listWidget = QtWidgets.QListWidget(parent=self.horizontalLayoutWidget_3)
        self.crear_items_listWidget.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b0b0b0;  /* Gris más claro */\n"
"    min-height: 30px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QListView {\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.crear_items_listWidget.setObjectName("crear_items_listWidget")
        self.horizontalLayout_3.addWidget(self.crear_items_listWidget)
        self.crear_orderList_tableWidget = QtWidgets.QTableWidget(parent=self.crearordenTab)
        self.crear_orderList_tableWidget.setGeometry(QtCore.QRect(420, 60, 361, 251))
        self.crear_orderList_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.crear_orderList_tableWidget.setObjectName("crear_orderList_tableWidget")
        self.crear_orderList_tableWidget.setColumnCount(0)
        self.crear_orderList_tableWidget.setRowCount(0)
        self.groupBox = QtWidgets.QGroupBox(parent=self.crearordenTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 380, 391, 101))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.crear_description_textEdit = QtWidgets.QTextEdit(parent=self.groupBox)
        self.crear_description_textEdit.setGeometry(QtCore.QRect(10, 30, 371, 61))
        self.crear_description_textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.crear_description_textEdit.setReadOnly(True)
        self.crear_description_textEdit.setObjectName("crear_description_textEdit")
        self.tabs.addTab(self.crearordenTab, "")
        self.ordenesTab = QtWidgets.QWidget()
        self.ordenesTab.setObjectName("ordenesTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.ordenesTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 401, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.verticalLayoutWidget)
        self.treeView.setStyleSheet("QTreeView{\n"
"    background-color: white;\n"
"}\n"
"\n"
"")
        self.treeView.setObjectName("treeView")
        self.treeView.header().setMinimumSectionSize(39)
        self.verticalLayout.addWidget(self.treeView)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 410, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: black;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(430, 50, 91, 21))
        self.label.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(570, 50, 91, 21))
        self.label_2.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(730, 50, 51, 21))
        self.label_3.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(310, 410, 211, 61))
        self.label_7.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(540, 340, 241, 51))
        self.label_8.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(430, 340, 101, 51))
        self.label_9.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 401, 41))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.listView = QtWidgets.QListView(parent=self.widget)
        self.listView.setGeometry(QtCore.QRect(430, 80, 351, 241))
        self.listView.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}")
        self.listView.setObjectName("listView")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 410, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 12;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: black;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_6.setAutoRepeatDelay(300)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.widget)
        self.tabs.addTab(self.ordenesTab, "")
        self.reportesTab = QtWidgets.QWidget()
        self.reportesTab.setObjectName("reportesTab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.reportesTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView_3 = QtWidgets.QListView(parent=self.gridLayoutWidget)
        self.listView_3.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}")
        self.listView_3.setObjectName("listView_3")
        self.gridLayout_2.addWidget(self.listView_3, 1, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.gridLayoutWidget)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
"                background-color: #333333;\n"
"                color: black;\n"
"                font-family: Arial;\n"
"                border-radius: 10px;\n"
"            }\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"                background-color: #444444;\n"
"                color: white;\n"
"                selection-background-color: orange;\n"
"                selection-color: white;\n"
"            }\n"
"            QCalendarWidget QAbstractItemView:disabled {\n"
"                color: #777777;\n"
"            }\n"
"            QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"                background-color: #555555;\n"
"            }\n"
"            QCalendarWidget QToolButton {\n"
"                color: white;\n"
"                background-color: #555555;\n"
"                border: none;\n"
"            }\n"
"\n"
" QCalendarWidget QToolButton::hover {\n"
"                background-color: orange;\n"
"                color: black;\n"
"            }\n"
"            QCalendarWidget QToolButton::pressed {\n"
"                background-color: #ff6600;\n"
"                color: white;\n"
"            }\n"
"            QCalendarWidget QToolButton::disabled {\n"
"                background-color: #555555;\n"
"                color: #777777;\n"
"            }")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_2.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    color: black;\n"
"    width: 50px;\n"
"    height: 50px;\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.5s, transform 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    color: black;\n"
"    cursor: pointer;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.tabs.addTab(self.reportesTab, "")
        self.inventarioTab = QtWidgets.QWidget()
        self.inventarioTab.setObjectName("inventarioTab")
        self.inv_products_list_widget = QtWidgets.QListWidget(parent=self.inventarioTab)
        self.inv_products_list_widget.setGeometry(QtCore.QRect(20, 60, 399, 401))
        self.inv_products_list_widget.setStyleSheet("QListView{\n"
"    background-color: white;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b0b0b0;  /* Gris más claro */\n"
"    min-height: 30px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 0px;\n"
"}\n"
"\n"
"\n"
"")
        self.inv_products_list_widget.setObjectName("inv_products_list_widget")
        self.label_4 = QtWidgets.QLabel(parent=self.inventarioTab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.label_4.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.inventarioTab)
        self.groupBox_5.setGeometry(QtCore.QRect(460, 80, 311, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"        border: 2px solid pink; /* Color y grosor del borde */\n"
"        border-radius: 5px; /* Bordes redondeados */\n"
"        margin-top: 10px; /* Espacio entre el borde y el título */\n"
"        background-color: white;\n"
"        padding: 10px; /* Espacio interno del contenido */\n"
"    }\n"
"QGroupBox * {\n"
"        background-color: white;  /* Aplica el color de fondo a todos los widgets hijos */\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top center; /* Posición del título */\n"
"        padding: 0 5px; /* Espacio alrededor del título */\n"
"        color: black; /* Color del texto del título */\n"
"        font-weight: bold; /* Negrita para el título */\n"
"    }")
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 291, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.inv_name_line_edit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.inv_name_line_edit.setStyleSheet("QLineEdit{\n"
"    background-color: white;\n"
"}")
        self.inv_name_line_edit.setObjectName("inv_name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inv_name_line_edit)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.inv_cantidad_spin_box = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget_2)
        self.inv_cantidad_spin_box.setStyleSheet("QSpinBox{\n"
"    background-color: white;\n"
"}")
        self.inv_cantidad_spin_box.setObjectName("inv_cantidad_spin_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inv_cantidad_spin_box)
        self.label_12 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_12.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.inv_precio_double_spin_box = QtWidgets.QDoubleSpinBox(parent=self.verticalLayoutWidget_2)
        self.inv_precio_double_spin_box.setStyleSheet("QDoubleSpinBox{\n"
"    background-color: white;\n"
"}")
        self.inv_precio_double_spin_box.setObjectName("inv_precio_double_spin_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inv_precio_double_spin_box)
        self.label_13 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_13.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.inv_descripcion_item = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_2)
        self.inv_descripcion_item.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"}")
        self.inv_descripcion_item.setObjectName("inv_descripcion_item")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inv_descripcion_item)
        self.label_17 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_17)
        self.inv_tipo_producto_combo_box = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        self.inv_tipo_producto_combo_box.setObjectName("inv_tipo_producto_combo_box")
        self.inv_tipo_producto_combo_box.addItem("")
        self.inv_tipo_producto_combo_box.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inv_tipo_producto_combo_box)
        self.inv_elegir_imagen_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.inv_elegir_imagen_button.setStyleSheet("QPushButton{\n"
"    background-color: pink;\n"
"}")
        self.inv_elegir_imagen_button.setObjectName("inv_elegir_imagen_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inv_elegir_imagen_button)
        self.inv_imagen_ingrediente = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.inv_imagen_ingrediente.setMaximumSize(QtCore.QSize(64, 64))
        self.inv_imagen_ingrediente.setText("")
        self.inv_imagen_ingrediente.setPixmap(QtGui.QPixmap("ui\\../../../imagenes/galleta2.jpg"))
        self.inv_imagen_ingrediente.setScaledContents(True)
        self.inv_imagen_ingrediente.setObjectName("inv_imagen_ingrediente")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inv_imagen_ingrediente)
        self.inv_crear_ingrediente = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inv_crear_ingrediente.sizePolicy().hasHeightForWidth())
        self.inv_crear_ingrediente.setSizePolicy(sizePolicy)
        self.inv_crear_ingrediente.setStyleSheet("QPushButton{\n"
"    background-color: pink;\n"
"}")
        self.inv_crear_ingrediente.setObjectName("inv_crear_ingrediente")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inv_crear_ingrediente)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.inv_seleccionado_label = QtWidgets.QLabel(parent=self.inventarioTab)
        self.inv_seleccionado_label.setGeometry(QtCore.QRect(450, 20, 331, 51))
        self.inv_seleccionado_label.setStyleSheet("QLabel{    \n"
"    color: black;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    background-color: orange;\n"
"    border-radius: 10px;\n"
"}")
        self.inv_seleccionado_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inv_seleccionado_label.setObjectName("inv_seleccionado_label")
        self.inv_busqueda_line_edit = QtWidgets.QLineEdit(parent=self.inventarioTab)
        self.inv_busqueda_line_edit.setGeometry(QtCore.QRect(150, 20, 261, 22))
        self.inv_busqueda_line_edit.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"}")
        self.inv_busqueda_line_edit.setObjectName("inv_busqueda_line_edit")
        self.tabs.addTab(self.inventarioTab, "")
        self.agregarproductoTab = QtWidgets.QWidget()
        self.agregarproductoTab.setObjectName("agregarproductoTab")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.agregarproductoTab)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 20, 261, 441))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.add_labelDropImage = QtWidgets.QLabel(parent=self.groupBox_2)
        self.add_labelDropImage.setGeometry(QtCore.QRect(60, 20, 141, 131))
        self.add_labelDropImage.setAcceptDrops(True)
        self.add_labelDropImage.setText("")
        self.add_labelDropImage.setPixmap(QtGui.QPixmap("ui\\../imagenes/iconoGaleria.jpeg"))
        self.add_labelDropImage.setScaledContents(True)
        self.add_labelDropImage.setObjectName("add_labelDropImage")
        self.add_searchImageButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.add_searchImageButton.setGeometry(QtCore.QRect(10, 170, 241, 31))
        self.add_searchImageButton.setStyleSheet("color: black;\n"
"font-family: Segoe UI;\n"
"font-size: 14px;\n"
" font-weight: bold;\n"
"background-color: orange;\n"
"border-radius: 8px")
        self.add_searchImageButton.setObjectName("add_searchImageButton")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 220, 221, 201))
        self.groupBox_4.setStyleSheet("QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.add_labelImagePreview = QtWidgets.QLabel(parent=self.groupBox_4)
        self.add_labelImagePreview.setGeometry(QtCore.QRect(10, 30, 221, 171))
        self.add_labelImagePreview.setText("")
        self.add_labelImagePreview.setObjectName("add_labelImagePreview")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.agregarproductoTab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 421, 451))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label_14.setStyleSheet("font-family: Segoe UI;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.label_14.setObjectName("label_14")
        self.add_lineEditProductName = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.add_lineEditProductName.setGeometry(QtCore.QRect(10, 60, 401, 22))
        self.add_lineEditProductName.setStyleSheet("background-color: white;\n"
"font-family: Segoe UI;\n"
"font-size: 15px;")
        self.add_lineEditProductName.setObjectName("add_lineEditProductName")
        self.add_textEditDescription = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.add_textEditDescription.setGeometry(QtCore.QRect(10, 200, 401, 151))
        self.add_textEditDescription.setStyleSheet("background-color: white;\n"
"font-family: Segoe UI;\n"
"font-size: 15px;")
        self.add_textEditDescription.setObjectName("add_textEditDescription")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_15.setStyleSheet("font-family: Segoe UI;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.label_16.setStyleSheet("font-family: Segoe UI;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.label_16.setObjectName("label_16")
        self.add_lineEditPrice = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.add_lineEditPrice.setGeometry(QtCore.QRect(10, 130, 401, 22))
        self.add_lineEditPrice.setStyleSheet("background-color: white;\n"
"font-family: Segoe UI;\n"
"font-size: 15px;")
        self.add_lineEditPrice.setObjectName("add_lineEditPrice")
        self.add_saveChangesButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.add_saveChangesButton.setGeometry(QtCore.QRect(10, 370, 401, 71))
        self.add_saveChangesButton.setStyleSheet("color: black;\n"
"font-family: Segoe UI;\n"
"font-size: 16px;\n"
" font-weight: bold;\n"
"background-color: orange;\n"
"border-radius: 8px")
        self.add_saveChangesButton.setObjectName("add_saveChangesButton")
        self.tabs.addTab(self.agregarproductoTab, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReportes = QtWidgets.QMenu(parent=self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuInventario = QtWidgets.QMenu(parent=self.menubar)
        self.menuInventario.setObjectName("menuInventario")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuInventario.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SellingSoftwareForMollysCookies"))
        self.crear_createorder_button.setText(_translate("MainWindow", "Crear orden"))
        self.crear_totalprice_button.setText(_translate("MainWindow", "Precio total"))
        self.product_label.setText(_translate("MainWindow", "Producto"))
        self.quantity_label.setText(_translate("MainWindow", "Cantidad"))
        self.total_label.setText(_translate("MainWindow", "Subtotal"))
        self.groupBox.setTitle(_translate("MainWindow", "Características"))
        self.crear_description_textEdit.setPlaceholderText(_translate("MainWindow", "Caracteristicas del producto"))
        self.tabs.setTabText(self.tabs.indexOf(self.crearordenTab), _translate("MainWindow", "Crear"))
        self.pushButton_3.setText(_translate("MainWindow", "Eliminar orden"))
        self.label.setText(_translate("MainWindow", "Producto"))
        self.label_2.setText(_translate("MainWindow", "Cantidad"))
        self.label_3.setText(_translate("MainWindow", "Total"))
        self.label_7.setText(_translate("MainWindow", "Total a pagar"))
        self.label_8.setText(_translate("MainWindow", "Caracteristicas"))
        self.label_9.setText(_translate("MainWindow", "Imagen del producto"))
        self.pushButton_6.setText(_translate("MainWindow", "Eliminar item"))
        self.tabs.setTabText(self.tabs.indexOf(self.ordenesTab), _translate("MainWindow", "Ordenes"))
        self.pushButton.setText(_translate("MainWindow", "Seleccionar"))
        self.tabs.setTabText(self.tabs.indexOf(self.reportesTab), _translate("MainWindow", "Reportes"))
        self.label_4.setText(_translate("MainWindow", "Ingredientes"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Atributos del ingrediente"))
        self.label_5.setText(_translate("MainWindow", "Nombre"))
        self.label_6.setText(_translate("MainWindow", "Cantidad disponible"))
        self.label_12.setText(_translate("MainWindow", "Precio unitario"))
        self.label_13.setText(_translate("MainWindow", "Descripción"))
        self.label_17.setText(_translate("MainWindow", "Tipo de producto"))
        self.inv_tipo_producto_combo_box.setItemText(0, _translate("MainWindow", "Unidad"))
        self.inv_tipo_producto_combo_box.setItemText(1, _translate("MainWindow", "Kg"))
        self.inv_elegir_imagen_button.setText(_translate("MainWindow", "Cargar imagen"))
        self.inv_crear_ingrediente.setText(_translate("MainWindow", "Crear ingrediente"))
        self.inv_seleccionado_label.setText(_translate("MainWindow", "Seleccionado"))
        self.tabs.setTabText(self.tabs.indexOf(self.inventarioTab), _translate("MainWindow", "Inventario"))
        self.add_searchImageButton.setText(_translate("MainWindow", "Agregar imagen"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Vista previa"))
        self.label_14.setText(_translate("MainWindow", "Nombre del producto"))
        self.label_15.setText(_translate("MainWindow", "Descripción"))
        self.label_16.setText(_translate("MainWindow", "Precio"))
        self.add_saveChangesButton.setText(_translate("MainWindow", "Guardar cambios"))
        self.tabs.setTabText(self.tabs.indexOf(self.agregarproductoTab), _translate("MainWindow", "Agregar Producto"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivos"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuInventario.setTitle(_translate("MainWindow", "Inventario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
