# Form implementation generated from reading ui file 'D:\Coding\Python\PyQt6UIExports\start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabs.setStyleSheet("QTabBar::tab {\n"
"        border: 1px solid black;\n"
"        padding: 10px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"        background: rgb(170, 170, 170);\n"
"        font-weight: bold;\n"
"}\n"
"QTabBar::tab:hover {\n"
"        background: rgb(200, 200, 200);\n"
"}")
        self.tabs.setObjectName("tabs")
        self.ordenesTab = QtWidgets.QWidget()
        self.ordenesTab.setObjectName("ordenesTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.ordenesTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 391, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.verticalLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout.addWidget(self.widget)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.tabs.addTab(self.ordenesTab, "")
        self.inventarioTab = QtWidgets.QWidget()
        self.inventarioTab.setObjectName("inventarioTab")
        self.tabs.addTab(self.inventarioTab, "")
        self.reportesTab = QtWidgets.QWidget()
        self.reportesTab.setObjectName("reportesTab")
        self.tabs.addTab(self.reportesTab, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReportes = QtWidgets.QMenu(parent=self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuInventario = QtWidgets.QMenu(parent=self.menubar)
        self.menuInventario.setObjectName("menuInventario")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuInventario.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_3.setStyleSheet("QPushButton {"
                                        "height: 100px;"
                                        "border: 2px solid black;"
                                        "border-radius: 10px;"
                                        "background-color: white;"
                                        "color: black;"
                                        "}")

        # Animacion
        self.animation = QtCore.QPropertyAnimation(self.pushButton_3, b"color")
        self.animation.setDuration(300)

        self.pushButton_3.setMouseTracking(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SellingSoftwareForMollysCookies"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.tabs.setTabText(self.tabs.indexOf(self.ordenesTab), _translate("MainWindow", "Ordenes"))
        self.tabs.setTabText(self.tabs.indexOf(self.inventarioTab), _translate("MainWindow", "Inventario"))
        self.tabs.setTabText(self.tabs.indexOf(self.reportesTab), _translate("MainWindow", "Reportes"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivos"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuInventario.setTitle(_translate("MainWindow", "Inventario"))
